server:
  port: 8081
spring:
  application:
    name: marketMgr
  profiles:
    active: prod #默认配置
  servlet:
    multipart:
      enabled: true
      max-file-size: 30MB
mybatis:
  mapper-locations:
    - classpath*:com/pht/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
jwt:
  security: marketMgr
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  tokenHead: 'Bearer'
  tokenHeader: Authorization #JWT存储的请求头
  compHead: 'COMPCODE'

secure:
  ignored:
    urls: #安全路径白名单
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /druid/**
      - /admin/login
      - /admin/register
      - /admin/info
      - /admin/logout
      - /minio/upload
    defSourceUrl: #不需要数据源 即连接数据库操作只能是默认数据源
      - /admin/queryComp
debug: true